version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./suricata-logs:/var/log/suricata
      - ./zeek-logs:/opt/zeek/logs
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash

  suricata:
    image: jasonish/suricata:latest
    privileged: true
    volumes:
      - ./suricata.yaml:/etc/suricata/suricata.yaml
      - ./suricata-logs:/var/log/suricata
    command: suricata -c /etc/suricata/suricata.yaml -i eth0
    networks:
      - elk

  zeek:
    image: zeek/zeek:latest
    privileged: true
    volumes:
      - ./zeek-logs:/opt/zeek/logs
    command: zeek -i eth0
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  es_data:
