filebeat.inputs:
  - type: log
    paths:
      - /var/log/suricata/eve.json
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
  - type: log
    paths:
      - /opt/zeek/logs/current/*.log
    processors:
      - dissect:
          tokenizer: "%{ts}\t%{uid}\t%{id.orig_h}\t%{id.orig_p}\t%{id.resp_h}\t%{id.resp_p}\t%{proto}\t%{service}\t%{duration}\t%{orig_bytes}\t%{resp_bytes}\t%{conn_state}\t%{local_orig}\t%{local_resp}\t%{missed_bytes}\t%{history}\t%{orig_pkts}\t%{orig_ip_bytes}\t%{resp_pkts}\t%{resp_ip_bytes}\t%{tunnel_parents}"
          field: "message"
          target_prefix: "zeek"
output.logstash:
  hosts: ["logstash:5044"]
